import { NextRequest, NextResponse } from 'next/server';
import { ensureSchema, query } from '@/lib/db';
import { createClient } from '@/lib/supabase/server';
import { clients as staticClients, makePrimeIVClient, makeCustomClient, slugify } from '@/lib/clients';
import { suggestMergeVars } from '@/lib/merge-vars';
import { spawnClientTasks } from '@/lib/team-tasks';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// Staff auto-assigned to every new Prime IV location (Sable + Vanessa).
const DEFAULT_PRIME_STAFF = ['admin@mothernatureagency.com', 'info@mothernatureagency.com'];

/**
 * Custom (dynamically-added) Prime IV clients.
 *
 * Staff onboard a new Prime IV location by typing its name; the full client
 * config is generated by makePrimeIVClient. Stored in custom_clients and
 * merged into the client list by ClientContext so it shows up in every
 * staff selector.
 *
 * GET    /api/clients      → list custom clients (raw rows)
 * POST   /api/clients      → { name, staffEmails? }  create a new client and
 *                            assign the chosen teammates to it
 * DELETE /api/clients?id=  → remove a custom client
 */

async function role(): Promise<string> {
  try {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    return ((user?.user_metadata as Record<string, unknown> | null)?.role as string) || (user ? 'staff' : '');
  } catch { return ''; }
}

export async function GET() {
  await ensureSchema();
  const { rows } = await query(
    `select id, name, short_name, location, logo_url, industry, brand_from, brand_to, notes, created_at from custom_clients order by created_at asc`,
  );
  return NextResponse.json({ items: rows });
}

export async function POST(req: NextRequest) {
  await ensureSchema();
  const r = await role();
  if (!r) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (r === 'client') return NextResponse.json({ error: 'Only staff can add clients' }, { status: 403 });

  let body: any;
  try { body = await req.json(); } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }
  const name = (body?.name || '').toString().trim();
  const logoUrl = (body?.logoUrl || '').toString().trim() || null;
  const industry = (body?.industry || '').toString().trim() || null;
  const brandFrom = (body?.brandFrom || '').toString().trim() || null;
  const brandTo = (body?.brandTo || '').toString().trim() || null;
  const notes = (body?.notes || '').toString().trim() || null;
  if (!name) return NextResponse.json({ error: 'name required' }, { status: 400 });

  // Prime IV location (name only) vs. an "other business" with its own
  // industry/branding. The generic factory picks the id (plain slug) while
  // Prime IV clients get the prime-iv- prefix.
  const isGeneric = !!(industry || brandFrom || brandTo);
  const client = isGeneric
    ? makeCustomClient({ name, logoUrl: logoUrl || undefined, industry: industry || undefined, brandFrom: brandFrom || undefined, brandTo: brandTo || undefined, notes: notes || undefined })
    : makePrimeIVClient({ name, logoUrl: logoUrl || undefined });
  if (!slugify(name)) {
    return NextResponse.json({ error: 'Please enter a valid name' }, { status: 400 });
  }

  // Guard against colliding with a built-in client id.
  if (staticClients.some((c) => c.id === client.id)) {
    return NextResponse.json({ error: `That client already exists (${client.name})` }, { status: 409 });
  }

  try {
    const { rows } = await query(
      `insert into custom_clients (id, name, short_name, location, logo_url, industry, brand_from, brand_to, notes)
       values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       on conflict (id) do nothing
       returning id, name, short_name, location, logo_url, industry, brand_from, brand_to, notes, created_at`,
      [client.id, client.name, client.shortName, client.location || null, logoUrl, industry, brandFrom, brandTo, notes],
    );
    if (rows.length === 0) {
      return NextResponse.json({ error: `That client already exists (${client.name})` }, { status: 409 });
    }

    // Pre-fill caption merge fields so {{location}}, {{linktree}} and
    // {{website}} resolve from the first post instead of publishing raw. These
    // are guesses derived from the name — staff correct them in the Content
    // Tracker. Only seeded when nothing is stored yet, so this never clobbers.
    try {
      const suggested = suggestMergeVars({
        name: client.name,
        location: client.location,
        isPrimeIV: !isGeneric,
        website: client.links?.website,
      });
      await query(
        `insert into client_kv (client_id, key, value, updated_at)
         values ($1, 'merge_vars', $2::jsonb, now())
         on conflict (client_id, key) do nothing`,
        [client.id, JSON.stringify(suggested)],
      );
    } catch { /* non-fatal */ }

    // Staff coverage from day one. The onboarding form can name who to
    // assign; with nothing chosen, Prime IV locations fall back to the
    // default Prime team. Never blocks client creation.
    const chosen: string[] = Array.isArray(body?.staffEmails)
      ? body.staffEmails
          .map((e: unknown) => String(e || '').trim().toLowerCase())
          .filter((e: string) => /^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e))
      : [];
    const toAssign = chosen.length > 0 ? chosen : (isGeneric ? [] : DEFAULT_PRIME_STAFF);
    if (toAssign.length > 0) {
      try {
        for (const email of Array.from(new Set(toAssign))) {
          await query(`insert into staff_assignments (staff_email, client_id) values ($1, $2) on conflict do nothing`, [email, client.id]);
        }
      } catch { /* non-fatal */ }
    }

    // Per-new-client Team Tasks: any recurring template marked "each new
    // client" spawns its onboarding tasks now, assigned and dated. Idempotent
    // (spawn log keyed by client id) and never blocks client creation.
    try { await spawnClientTasks(client.id, client.shortName || client.name); } catch { /* non-fatal */ }

    return NextResponse.json({ item: rows[0], client });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'Could not add client' }, { status: 500 });
  }
}

// PATCH /api/clients  { id, logoUrl } — update a custom client's logo.
export async function PATCH(req: NextRequest) {
  await ensureSchema();
  const r = await role();
  if (!r) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (r === 'client') return NextResponse.json({ error: 'Only staff can edit clients' }, { status: 403 });

  let body: any;
  try { body = await req.json(); } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }
  const id = (body?.id || '').toString().trim();
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 });
  const logoUrl = (body?.logoUrl ?? '').toString().trim() || null;

  const { rows } = await query(
    `update custom_clients set logo_url = $1 where id = $2
     returning id, name, short_name, location, logo_url, created_at`,
    [logoUrl, id],
  );
  if (rows.length === 0) return NextResponse.json({ error: 'Not a custom client (built-ins can\'t be edited here)' }, { status: 404 });
  return NextResponse.json({ item: rows[0] });
}

export async function DELETE(req: NextRequest) {
  await ensureSchema();
  const r = await role();
  if (!r) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (r === 'client') return NextResponse.json({ error: 'Only staff can remove clients' }, { status: 403 });

  const id = req.nextUrl.searchParams.get('id');
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 });
  await query('delete from custom_clients where id = $1', [id]);
  return NextResponse.json({ ok: true });
}
