import { NextRequest, NextResponse } from 'next/server';
import { ensureSchema, query } from '@/lib/db';
import { createClient } from '@/lib/supabase/server';
import { clients as staticClients, makePrimeIVClient, slugify } from '@/lib/clients';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * Custom (dynamically-added) Prime IV clients.
 *
 * Staff onboard a new Prime IV location by typing its name; the full client
 * config is generated by makePrimeIVClient. Stored in custom_clients and
 * merged into the client list by ClientContext so it shows up in every
 * staff selector.
 *
 * GET    /api/clients      → list custom clients (raw rows)
 * POST   /api/clients      → { name }  create a new Prime IV client
 * DELETE /api/clients?id=  → remove a custom client
 */

async function role(): Promise<string> {
  try {
    const supabase = createClient();
    const { data: { user } } = await supabase.auth.getUser();
    return ((user?.user_metadata as Record<string, unknown> | null)?.role as string) || (user ? 'staff' : '');
  } catch { return ''; }
}

export async function GET() {
  await ensureSchema();
  const { rows } = await query(
    `select id, name, short_name, location, created_at from custom_clients order by created_at asc`,
  );
  return NextResponse.json({ items: rows });
}

export async function POST(req: NextRequest) {
  await ensureSchema();
  const r = await role();
  if (!r) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (r === 'client') return NextResponse.json({ error: 'Only staff can add clients' }, { status: 403 });

  let body: any;
  try { body = await req.json(); } catch { return NextResponse.json({ error: 'Invalid JSON' }, { status: 400 }); }
  const name = (body?.name || '').toString().trim();
  if (!name) return NextResponse.json({ error: 'name required' }, { status: 400 });

  // Generate the full config so we can derive/validate the id, then persist
  // just the identifying fields (the rest is regenerated on load).
  const client = makePrimeIVClient({ name });
  if (!slugify(client.location || client.name)) {
    return NextResponse.json({ error: 'Please enter a valid location name' }, { status: 400 });
  }

  // Guard against colliding with a built-in client id.
  if (staticClients.some((c) => c.id === client.id)) {
    return NextResponse.json({ error: `That location already exists (${client.name})` }, { status: 409 });
  }

  try {
    const { rows } = await query(
      `insert into custom_clients (id, name, short_name, location)
       values ($1, $2, $3, $4)
       on conflict (id) do nothing
       returning id, name, short_name, location, created_at`,
      [client.id, client.name, client.shortName, client.location || null],
    );
    if (rows.length === 0) {
      return NextResponse.json({ error: `That location already exists (${client.name})` }, { status: 409 });
    }
    return NextResponse.json({ item: rows[0], client });
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'Could not add client' }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  await ensureSchema();
  const r = await role();
  if (!r) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });
  if (r === 'client') return NextResponse.json({ error: 'Only staff can remove clients' }, { status: 403 });

  const id = req.nextUrl.searchParams.get('id');
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 });
  await query('delete from custom_clients where id = $1', [id]);
  return NextResponse.json({ ok: true });
}
